# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  test:all:
    desc: Run all testss
    cmds:
      - go test ./...
    env:
      RUN_INTEGRATION_TESTS: true

  test:
    desc: Run all testss
    cmds:
      - go test ./...
