// Code generated by "stringer -type=Type"; DO NOT EDIT.

package param

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Untyped-0]
	_ = x[Bool-1]
	_ = x[Int-2]
	_ = x[Float-3]
	_ = x[String-4]
}

const _Type_name = "UntypedBoolIntFloatString"

var _Type_index = [...]uint8{0, 7, 11, 14, 19, 25}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
